import { useState, useEffect, useMemo } from 'react';
import { type Node } from 'reactflow';
import { X, Trash2, Save, AlertCircle, Code, Plus, Trash, Layers } from 'lucide-react';
import type { CalmNode, CalmRelationship } from '../domain/calm';

interface SidebarProps {
  selectedNode: Node | null;
  allNodes: Node[];
  relationships: CalmRelationship[];
  onUpdate: (id: string, data: Partial<CalmNode>) => void;
  onDelete: (id: string) => void;
  onClose: () => void;
  onAddInterface?: (nodeId: string, interfaceId: string, protocol: string) => void;
  onDeleteInterface?: (nodeId: string, interfaceId: string) => void;
  onAddChildNode?: (composedOfId: string, childNodeId: string) => void;
  onRemoveChildNode?: (composedOfId: string, childNodeId: string) => void;
}

const Sidebar = ({ selectedNode, allNodes, relationships, onUpdate, onDelete, onClose, onAddInterface, onDeleteInterface, onAddChildNode, onRemoveChildNode }: SidebarProps) => {
  const [formData, setFormData] = useState<Partial<CalmNode>>({});

  useEffect(() => {
    if (selectedNode) {
      setFormData(selectedNode.data.calm);
    }
  }, [selectedNode]);

  // ComposedOf info - computed at top level to respect hooks rules
  const composedOfInfo = useMemo(() => {
    if (!selectedNode) return null;
    for (const rel of relationships) {
      const composedOfData = rel['relationship-type']?.['composed-of'];
      if (composedOfData && composedOfData.container === selectedNode.id) {
        return {
          id: rel['unique-id'],
          container: composedOfData.container,
          nodes: composedOfData.nodes || [],
        };
      }
    }
    return null;
  }, [relationships, selectedNode]);

  const availableChildNodes = useMemo(() => {
    if (!composedOfInfo || !selectedNode) return [];
    return allNodes.filter(n =>
      n.id !== selectedNode.id &&
      !composedOfInfo.nodes.includes(n.id)
    );
  }, [allNodes, composedOfInfo, selectedNode]);

  const getNodeLabel = (nodeId: string) => {
    const node = allNodes.find(n => n.id === nodeId);
    return node?.data?.label || nodeId;
  };

  if (!selectedNode) return null;

  // Read origin directly from the node data, not from formData (which is for editing)
  const origin = selectedNode.data.calm?._origin;
  const isDeletable = !origin || origin.type === 'explicit' ||
    (origin.type === 'loop' && origin.loopIndex === origin.loopMax);
  const isEditable = !origin || origin.type === 'explicit' || origin.type === 'loop';

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSave = () => {
    onUpdate(selectedNode.id, formData);
  };

  const getOriginBadge = () => {
    if (!origin) return null;

    const badges = {
      explicit: { color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: '🟢', label: 'Explicit' },
      loop: { color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', icon: '🔵', label: 'Loop Generated' },
      function: { color: 'bg-gray-500/20 text-gray-400 border-gray-500/30', icon: '⚪', label: 'Function Generated' },
    };

    const badge = badges[origin.type as keyof typeof badges];
    return (
      <div className={`inline-flex items-center gap-1.5 px-2 py-1 rounded-md border text-xs font-medium ${badge.color}`}>
        <span>{badge.icon}</span>
        <span>{badge.label}</span>
      </div>
    );
  };

  const getRestrictionMessage = () => {
    if (!origin) return null;

    if (origin.type === 'loop' && origin.loopIndex !== origin.loopMax) {
      return (
        <div className="flex items-start gap-2 p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-md text-yellow-400 text-xs">
          <AlertCircle size={14} className="mt-0.5 flex-shrink-0" />
          <div>
            <div className="font-semibold">Loop element {origin.loopIndex}/{origin.loopMax}</div>
            <div className="mt-1 text-yellow-400/80">Cannot delete (not last element). Editing affects the template.</div>
          </div>
        </div>
      );
    }

    if (origin.type === 'function') {
      return (
        <div className="flex items-start gap-2 p-3 bg-gray-500/10 border border-gray-500/30 rounded-md text-gray-400 text-xs">
          <Code size={14} className="mt-0.5 flex-shrink-0" />
          <div>
            <div className="font-semibold">Generated by function</div>
            <div className="mt-1 text-gray-400/80">Edit in Go code only</div>
          </div>
        </div>
      );
    }

    if (origin.type === 'loop' && origin.loopIndex === origin.loopMax) {
      return (
        <div className="flex items-start gap-2 p-3 bg-blue-500/10 border border-blue-500/30 rounded-md text-blue-400 text-xs">
          <AlertCircle size={14} className="mt-0.5 flex-shrink-0" />
          <div>
            <div className="font-semibold">Last loop element ({origin.loopIndex}/{origin.loopMax})</div>
            <div className="mt-1 text-blue-400/80">Deleting will decrease <code className="bg-blue-500/20 px-1 rounded">{origin.loopVar}</code> to {(origin.loopMax ?? 1) - 1}</div>
          </div>
        </div>
      );
    }

    return null;
  };

  return (
    <aside className="absolute right-0 top-0 h-full w-80 bg-slate-900 shadow-2xl border-l border-slate-800 z-[100] flex flex-col animate-in slide-in-from-right duration-200">
      <div className="p-4 border-b border-slate-800 bg-slate-900/50 flex justify-between items-center">
        <h2 className="font-bold text-slate-200 flex items-center gap-2">
          Node Properties
        </h2>
        <button onClick={onClose} className="text-slate-500 hover:text-slate-300 transition-colors">
          <X size={20} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-5">
        {origin && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Origin</label>
              {getOriginBadge()}
            </div>
            {getRestrictionMessage()}
            <div className="text-xs text-slate-500 space-y-0.5">
              <div>📄 {origin.file}:{origin.line}</div>
              {origin.funcName && <div>⚙️ {origin.funcName}()</div>}
            </div>
          </div>
        )}

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Unique ID</label>
          <input
            type="text"
            className="w-full p-2 bg-slate-950 border border-slate-800 rounded text-sm text-slate-400 cursor-not-allowed"
            value={selectedNode.id}
            readOnly
          />
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Name</label>
          <input
            name="name"
            type="text"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none transition-all"
            value={formData.name || ''}
            onChange={handleChange}
            disabled={!isEditable}
          />
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Type</label>
          <select
            name="node-type"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 outline-none focus:border-blue-500 transition-all"
            value={formData['node-type'] || ''}
            onChange={handleChange}
            disabled={!isEditable}
          >
            <option value="service">Service</option>
            <option value="database">Database</option>
            <option value="actor">Actor</option>
            <option value="system">System</option>
            <option value="queue">Queue</option>
          </select>
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Owner</label>
          <input
            name="owner"
            type="text"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 focus:border-blue-500 outline-none transition-all"
            value={formData.owner || ''}
            onChange={handleChange}
            disabled={!isEditable}
          />
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Description</label>
          <textarea
            name="description"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 outline-none focus:border-blue-500 transition-all h-24 resize-none"
            value={formData.description || ''}
            onChange={handleChange}
            disabled={!isEditable}
          />
        </div>

        {/* Interfaces Section */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Interfaces</label>
            {isEditable && onAddInterface && (
              <button
                type="button"
                onClick={() => {
                  const id = prompt('Enter Interface ID (e.g., http-api):');
                  if (id && id.trim()) {
                    const protocol = prompt('Enter Protocol (HTTP, gRPC, etc.):', 'HTTP');
                    if (protocol && protocol.trim()) {
                      onAddInterface(selectedNode.id, id.trim(), protocol.trim());
                    }
                  }
                }}
                className="text-xs text-blue-400 hover:text-blue-300 flex items-center gap-1"
              >
                <Plus size={12} /> Add
              </button>
            )}
          </div>
          {formData.interfaces && formData.interfaces.length > 0 ? (
            <div className="space-y-2">
              {formData.interfaces.map((iface: any) => (
                <div key={iface['unique-id']} className="bg-slate-800/50 border border-slate-700 rounded p-2 flex items-center justify-between group">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-mono text-blue-300">{iface['unique-id']}</span>
                      <span className="text-[10px] bg-slate-700 px-1.5 py-0.5 rounded text-slate-400">{iface.protocol}</span>
                    </div>
                    {(iface.port || iface.name) && (
                      <div className="text-[10px] text-slate-500 mt-0.5">
                        {iface.port && <span className="mr-2">:{iface.port}</span>}
                        {iface.name && <span>{iface.name}</span>}
                      </div>
                    )}
                  </div>
                  {isEditable && onDeleteInterface && (
                    <button
                      onClick={() => {
                        if (confirm(`Delete interface ${iface['unique-id']}?`)) {
                          onDeleteInterface(selectedNode.id, iface['unique-id']);
                        }
                      }}
                      className="text-slate-600 hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100"
                    >
                      <Trash size={12} />
                    </button>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div className="text-xs text-slate-600 italic border border-dashed border-slate-800 rounded p-2 text-center">
              No interfaces defined
            </div>
          )}
        </div>

        {/* ComposedOf Section (for container nodes) */}
        {selectedNode.data.isContainer && (
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Layers size={14} className="text-purple-400" />
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">ComposedOf Children</label>
            </div>
            {composedOfInfo ? (
              <div className="space-y-2">
                {composedOfInfo.nodes.map((nodeId) => (
                  <div key={nodeId} className="flex items-center justify-between bg-purple-900/20 border border-purple-800/30 rounded px-3 py-2 group">
                    <span className="text-sm text-slate-200">{getNodeLabel(nodeId)}</span>
                    {onRemoveChildNode && (
                      <button
                        onClick={() => {
                          if (confirm(`Remove "${getNodeLabel(nodeId)}" from this container?`)) {
                            onRemoveChildNode(composedOfInfo.id, nodeId);
                          }
                        }}
                        className="text-slate-600 hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100"
                      >
                        <Trash size={12} />
                      </button>
                    )}
                  </div>
                ))}
                {onAddChildNode && availableChildNodes.length > 0 && (
                  <select
                    onChange={(e) => {
                      if (e.target.value) {
                        onAddChildNode(composedOfInfo.id, e.target.value);
                        e.target.value = '';
                      }
                    }}
                    className="w-full bg-slate-950 border border-slate-700 rounded px-2 py-1.5 text-xs text-slate-400 focus:outline-none focus:border-purple-500"
                  >
                    <option value="">+ Add child node...</option>
                    {availableChildNodes.map((node) => (
                      <option key={node.id} value={node.id}>
                        {node.data?.label || node.id}
                      </option>
                    ))}
                  </select>
                )}
                <div className="text-[10px] text-slate-500 font-mono">{composedOfInfo.id}</div>
              </div>
            ) : (
              <div className="text-xs text-slate-600 italic border border-dashed border-slate-800 rounded p-2 text-center">
                No ComposedOf relationship yet
              </div>
            )}
          </div>
        )}

        {/* Metadata Section */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Metadata</label>
            {isEditable && (
              <button
                type="button"
                onClick={() => {
                  const key = prompt('Enter metadata key:');
                  if (key && key.trim()) {
                    const value = prompt('Enter metadata value:');
                    setFormData((prev) => ({
                      ...prev,
                      metadata: { ...(prev.metadata || {}), [key.trim()]: value || '' },
                    }));
                  }
                }}
                className="text-xs text-blue-400 hover:text-blue-300"
              >
                + Add
              </button>
            )}
          </div>
          {formData.metadata && Object.keys(formData.metadata).length > 0 ? (
            <div className="space-y-1.5">
              {Object.entries(formData.metadata).map(([key, value]) => (
                <div key={key} className="flex items-center gap-2">
                  <span className="text-xs text-slate-400 font-mono bg-slate-800 px-2 py-1 rounded">{key}</span>
                  <input
                    type="text"
                    className="flex-1 p-1.5 bg-slate-800 border border-slate-700 rounded text-xs text-slate-200 outline-none focus:border-blue-500"
                    value={String(value)}
                    onChange={(e) => {
                      setFormData((prev) => ({
                        ...prev,
                        metadata: { ...(prev.metadata || {}), [key]: e.target.value },
                      }));
                    }}
                    disabled={!isEditable}
                  />
                  {isEditable && (
                    <button
                      type="button"
                      onClick={() => {
                        setFormData((prev) => {
                          const newMeta = { ...(prev.metadata || {}) };
                          delete newMeta[key];
                          return { ...prev, metadata: newMeta };
                        });
                      }}
                      className="text-red-400 hover:text-red-300 text-xs"
                    >
                      ×
                    </button>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div className="text-xs text-slate-600 italic">No metadata</div>
          )}
        </div>
      </div>

      <div className="p-4 border-t border-slate-800 bg-slate-900/50 space-y-3">
        <button
          onClick={handleSave}
          disabled={!isEditable}
          className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-md font-semibold transition-all shadow-lg ${isEditable
            ? 'bg-blue-600 text-white hover:bg-blue-500 active:scale-95'
            : 'bg-slate-800 text-slate-600 cursor-not-allowed'
            }`}
        >
          <Save size={16} /> Save Changes
        </button>
        <button
          onClick={() => {
            if (confirm('Are you sure you want to delete this node? This will update the Go source code.')) {
              onDelete(selectedNode.id);
            }
          }}
          disabled={!isDeletable}
          className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-md font-semibold transition-all ${isDeletable
            ? 'bg-slate-800 text-red-400 border border-slate-700 hover:bg-red-950/30 hover:text-red-300 active:scale-95'
            : 'bg-slate-900 text-slate-700 border border-slate-800 cursor-not-allowed'
            }`}
        >
          <Trash2 size={16} /> Delete Node
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;
