import { useState, useEffect } from 'react';
import { type Node } from 'reactflow';
import { X, Trash2, Save, AlertCircle, Code } from 'lucide-react';
import type { CalmNode } from '../domain/calm';

interface SidebarProps {
  selectedNode: Node | null;
  onUpdate: (id: string, data: Partial<CalmNode>) => void;
  onDelete: (id: string) => void;
  onClose: () => void;
}

const Sidebar = ({ selectedNode, onUpdate, onDelete, onClose }: SidebarProps) => {
  const [formData, setFormData] = useState<Partial<CalmNode>>({});

  useEffect(() => {
    if (selectedNode) {
      setFormData(selectedNode.data.calm);
    }
  }, [selectedNode]);

  if (!selectedNode) return null;

  // Read origin directly from the node data, not from formData (which is for editing)
  const origin = selectedNode.data.calm?._origin;
  const isDeletable = !origin || origin.type === 'explicit' ||
    (origin.type === 'loop' && origin.loopIndex === origin.loopMax);
  const isEditable = !origin || origin.type === 'explicit' || origin.type === 'loop';

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSave = () => {
    onUpdate(selectedNode.id, formData);
  };

  const getOriginBadge = () => {
    if (!origin) return null;

    const badges = {
      explicit: { color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: '🟢', label: 'Explicit' },
      loop: { color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', icon: '🔵', label: 'Loop Generated' },
      function: { color: 'bg-gray-500/20 text-gray-400 border-gray-500/30', icon: '⚪', label: 'Function Generated' },
    };

    const badge = badges[origin.type as keyof typeof badges];
    return (
      <div className={`inline-flex items-center gap-1.5 px-2 py-1 rounded-md border text-xs font-medium ${badge.color}`}>
        <span>{badge.icon}</span>
        <span>{badge.label}</span>
      </div>
    );
  };

  const getRestrictionMessage = () => {
    if (!origin) return null;

    if (origin.type === 'loop' && origin.loopIndex !== origin.loopMax) {
      return (
        <div className="flex items-start gap-2 p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-md text-yellow-400 text-xs">
          <AlertCircle size={14} className="mt-0.5 flex-shrink-0" />
          <div>
            <div className="font-semibold">Loop element {origin.loopIndex}/{origin.loopMax}</div>
            <div className="mt-1 text-yellow-400/80">Cannot delete (not last element). Editing affects the template.</div>
          </div>
        </div>
      );
    }

    if (origin.type === 'function') {
      return (
        <div className="flex items-start gap-2 p-3 bg-gray-500/10 border border-gray-500/30 rounded-md text-gray-400 text-xs">
          <Code size={14} className="mt-0.5 flex-shrink-0" />
          <div>
            <div className="font-semibold">Generated by function</div>
            <div className="mt-1 text-gray-400/80">Edit in Go code only</div>
          </div>
        </div>
      );
    }

    if (origin.type === 'loop' && origin.loopIndex === origin.loopMax) {
      return (
        <div className="flex items-start gap-2 p-3 bg-blue-500/10 border border-blue-500/30 rounded-md text-blue-400 text-xs">
          <AlertCircle size={14} className="mt-0.5 flex-shrink-0" />
          <div>
            <div className="font-semibold">Last loop element ({origin.loopIndex}/{origin.loopMax})</div>
            <div className="mt-1 text-blue-400/80">Deleting will decrease <code className="bg-blue-500/20 px-1 rounded">{origin.loopVar}</code> to {(origin.loopMax ?? 1) - 1}</div>
          </div>
        </div>
      );
    }

    return null;
  };

  return (
    <aside className="absolute right-0 top-0 h-full w-80 bg-slate-900 shadow-2xl border-l border-slate-800 z-[100] flex flex-col animate-in slide-in-from-right duration-200">
      <div className="p-4 border-b border-slate-800 bg-slate-900/50 flex justify-between items-center">
        <h2 className="font-bold text-slate-200 flex items-center gap-2">
          Node Properties
        </h2>
        <button onClick={onClose} className="text-slate-500 hover:text-slate-300 transition-colors">
          <X size={20} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-5">
        {origin && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Origin</label>
              {getOriginBadge()}
            </div>
            {getRestrictionMessage()}
            <div className="text-xs text-slate-500 space-y-0.5">
              <div>📄 {origin.file}:{origin.line}</div>
              {origin.funcName && <div>⚙️ {origin.funcName}()</div>}
            </div>
          </div>
        )}

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Unique ID</label>
          <input
            type="text"
            className="w-full p-2 bg-slate-950 border border-slate-800 rounded text-sm text-slate-400 cursor-not-allowed"
            value={selectedNode.id}
            readOnly
          />
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Name</label>
          <input
            name="name"
            type="text"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none transition-all"
            value={formData.name || ''}
            onChange={handleChange}
            disabled={!isEditable}
          />
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Type</label>
          <select
            name="node-type"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 outline-none focus:border-blue-500 transition-all"
            value={formData['node-type'] || ''}
            onChange={handleChange}
            disabled={!isEditable}
          >
            <option value="service">Service</option>
            <option value="database">Database</option>
            <option value="actor">Actor</option>
            <option value="system">System</option>
            <option value="queue">Queue</option>
          </select>
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Owner</label>
          <input
            name="owner"
            type="text"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 focus:border-blue-500 outline-none transition-all"
            value={formData.owner || ''}
            onChange={handleChange}
            disabled={!isEditable}
          />
        </div>

        <div className="space-y-1">
          <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider">Description</label>
          <textarea
            name="description"
            className="w-full p-2 bg-slate-800 border border-slate-700 rounded text-sm text-slate-200 outline-none focus:border-blue-500 transition-all h-24 resize-none"
            value={formData.description || ''}
            onChange={handleChange}
            disabled={!isEditable}
          />
        </div>
      </div>

      <div className="p-4 border-t border-slate-800 bg-slate-900/50 space-y-3">
        <button
          onClick={handleSave}
          disabled={!isEditable}
          className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-md font-semibold transition-all shadow-lg ${isEditable
            ? 'bg-blue-600 text-white hover:bg-blue-500 active:scale-95'
            : 'bg-slate-800 text-slate-600 cursor-not-allowed'
            }`}
        >
          <Save size={16} /> Save Changes
        </button>
        <button
          onClick={() => {
            if (confirm('Are you sure you want to delete this node? This will update the Go source code.')) {
              onDelete(selectedNode.id);
            }
          }}
          disabled={!isDeletable}
          className={`w-full flex items-center justify-center gap-2 py-2.5 rounded-md font-semibold transition-all ${isDeletable
            ? 'bg-slate-800 text-red-400 border border-slate-700 hover:bg-red-950/30 hover:text-red-300 active:scale-95'
            : 'bg-slate-900 text-slate-700 border border-slate-800 cursor-not-allowed'
            }`}
        >
          <Trash2 size={16} /> Delete Node
        </button>
      </div>
    </aside>
  );
};

export default Sidebar;
