package domain

import (
	"runtime"
	"strings"
)

// OriginType indicates how a node was created.
type OriginType string

const (
	// OriginExplicit means the node was defined directly (GUI: full edit allowed)
	OriginExplicit OriginType = "explicit"
	// OriginLoop means the node was created in a loop (GUI: last element only deletable)
	OriginLoop OriginType = "loop"
	// OriginFunction means the node was created by a helper function (GUI: view only)
	OriginFunction OriginType = "function"
)

// NodeOrigin tracks the source location and generation context of a node.
type NodeOrigin struct {
	Type      OriginType `json:"type"`
	File      string     `json:"file"`
	Line      int        `json:"line"`
	FuncName  string     `json:"funcName,omitempty"`
	LoopIndex int        `json:"loopIndex,omitempty"` // 1-based index in loop
	LoopMax   int        `json:"loopMax,omitempty"`   // total iterations (if known)
	LoopVar   string     `json:"loopVar,omitempty"`   // name of the loop control variable
}

// LoopContext holds the current loop iteration context.
// Use Architecture.WithinLoop() to set this before defining nodes in a loop.
type LoopContext struct {
	VarName string // e.g., "numGateways"
	Index   int    // 1-based current index
	Max     int    // total iterations
}

// DetectOrigin analyzes the call stack to determine how the node was created.
// skipFrames should be set to skip internal frames (typically 2 for DefineNode).
// loopCtx is the current loop context, obtained from Architecture.GetLoopContext().
func DetectOrigin(skipFrames int, loopCtx *LoopContext) *NodeOrigin {
	origin := &NodeOrigin{Type: OriginExplicit}

	// Check if we're in a loop context
	if loopCtx != nil {
		origin.Type = OriginLoop
		origin.LoopIndex = loopCtx.Index
		origin.LoopMax = loopCtx.Max
		origin.LoopVar = loopCtx.VarName
	}

	pc := make([]uintptr, 10)
	n := runtime.Callers(skipFrames, pc)
	if n == 0 {
		return origin
	}

	frames := runtime.CallersFrames(pc[:n])

	for {
		frame, more := frames.Next()

		// Skip standard library and runtime frames
		if strings.HasPrefix(frame.Function, "runtime.") {
			if !more {
				break
			}
			continue
		}

		// Extract file and line from the first meaningful frame
		if origin.File == "" {
			origin.File = shortenPath(frame.File)
			origin.Line = frame.Line
			origin.FuncName = extractFuncName(frame.Function)
		}

		if !more {
			break
		}
	}

	return origin
}

// shortenPath extracts the last two path components for readability.
func shortenPath(path string) string {
	parts := strings.Split(path, "/")
	if len(parts) > 2 {
		return strings.Join(parts[len(parts)-2:], "/")
	}
	return path
}

// extractFuncName extracts just the function name from a fully qualified name.
func extractFuncName(fullName string) string {
	parts := strings.Split(fullName, ".")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return fullName
}

// IsEditable returns true if the node can be edited in the GUI.
func (o *NodeOrigin) IsEditable() bool {
	return o.Type == OriginExplicit || o.Type == OriginLoop
}

// IsDeletable returns true if the node can be deleted in the GUI.
func (o *NodeOrigin) IsDeletable() bool {
	if o.Type == OriginExplicit {
		return true
	}
	if o.Type == OriginLoop && o.LoopMax > 0 && o.LoopIndex == o.LoopMax {
		return true // Only last element in loop is deletable
	}
	return false
}

// Restriction returns a human-readable restriction message if any.
func (o *NodeOrigin) Restriction() string {
	switch o.Type {
	case OriginLoop:
		if o.LoopIndex == o.LoopMax {
			return ""
		}
		return "Generated by loop - cannot delete (not last element)"
	case OriginFunction:
		return "Generated by function - edit in Go code only"
	default:
		return ""
	}
}
